// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package task_create

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Create(ctx context.Context, task domain.Task) (int64, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) (int64, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) int64); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - task domain.Task
func (_e *MockTaskRepository_Expecter) Create(ctx any, task any) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, task)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(ctx context.Context, task domain.Task)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Task
		if args[1] != nil {
			arg1 = args[1].(domain.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(n int64, err error) *MockTaskRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(ctx context.Context, task domain.Task) (int64, error)) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByID(ctx context.Context, taskID int64) (domain.Task, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (domain.Task, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) domain.Task); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTaskRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int64
func (_e *MockTaskRepository_Expecter) GetByID(ctx any, taskID any) *MockTaskRepository_GetByID_Call {
	return &MockTaskRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, taskID)}
}

func (_c *MockTaskRepository_GetByID_Call) Run(run func(ctx context.Context, taskID int64)) *MockTaskRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) Return(task domain.Task, err error) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, taskID int64) (domain.Task, error)) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamAccess creates a new instance of MockTeamAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamAccess {
	mock := &MockTeamAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamAccess is an autogenerated mock type for the TeamAccess type
type MockTeamAccess struct {
	mock.Mock
}

type MockTeamAccess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamAccess) EXPECT() *MockTeamAccess_Expecter {
	return &MockTeamAccess_Expecter{mock: &_m.Mock}
}

// EnsureAssigneeMember provides a mock function for the type MockTeamAccess
func (_mock *MockTeamAccess) EnsureAssigneeMember(ctx context.Context, teamID int64, assigneeID int64) error {
	ret := _mock.Called(ctx, teamID, assigneeID)

	if len(ret) == 0 {
		panic("no return value specified for EnsureAssigneeMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, teamID, assigneeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamAccess_EnsureAssigneeMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureAssigneeMember'
type MockTeamAccess_EnsureAssigneeMember_Call struct {
	*mock.Call
}

// EnsureAssigneeMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
//   - assigneeID int64
func (_e *MockTeamAccess_Expecter) EnsureAssigneeMember(ctx any, teamID any, assigneeID any) *MockTeamAccess_EnsureAssigneeMember_Call {
	return &MockTeamAccess_EnsureAssigneeMember_Call{Call: _e.mock.On("EnsureAssigneeMember", ctx, teamID, assigneeID)}
}

func (_c *MockTeamAccess_EnsureAssigneeMember_Call) Run(run func(ctx context.Context, teamID int64, assigneeID int64)) *MockTeamAccess_EnsureAssigneeMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTeamAccess_EnsureAssigneeMember_Call) Return(err error) *MockTeamAccess_EnsureAssigneeMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamAccess_EnsureAssigneeMember_Call) RunAndReturn(run func(ctx context.Context, teamID int64, assigneeID int64) error) *MockTeamAccess_EnsureAssigneeMember_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureTeamMember provides a mock function for the type MockTeamAccess
func (_mock *MockTeamAccess) EnsureTeamMember(ctx context.Context, teamID int64, actorID int64) error {
	ret := _mock.Called(ctx, teamID, actorID)

	if len(ret) == 0 {
		panic("no return value specified for EnsureTeamMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, teamID, actorID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamAccess_EnsureTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureTeamMember'
type MockTeamAccess_EnsureTeamMember_Call struct {
	*mock.Call
}

// EnsureTeamMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
//   - actorID int64
func (_e *MockTeamAccess_Expecter) EnsureTeamMember(ctx any, teamID any, actorID any) *MockTeamAccess_EnsureTeamMember_Call {
	return &MockTeamAccess_EnsureTeamMember_Call{Call: _e.mock.On("EnsureTeamMember", ctx, teamID, actorID)}
}

func (_c *MockTeamAccess_EnsureTeamMember_Call) Run(run func(ctx context.Context, teamID int64, actorID int64)) *MockTeamAccess_EnsureTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTeamAccess_EnsureTeamMember_Call) Return(err error) *MockTeamAccess_EnsureTeamMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamAccess_EnsureTeamMember_Call) RunAndReturn(run func(ctx context.Context, teamID int64, actorID int64) error) *MockTeamAccess_EnsureTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskCacheInvalidator creates a new instance of MockTaskCacheInvalidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskCacheInvalidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskCacheInvalidator {
	mock := &MockTaskCacheInvalidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskCacheInvalidator is an autogenerated mock type for the TaskCacheInvalidator type
type MockTaskCacheInvalidator struct {
	mock.Mock
}

type MockTaskCacheInvalidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskCacheInvalidator) EXPECT() *MockTaskCacheInvalidator_Expecter {
	return &MockTaskCacheInvalidator_Expecter{mock: &_m.Mock}
}

// InvalidateTeam provides a mock function for the type MockTaskCacheInvalidator
func (_mock *MockTaskCacheInvalidator) InvalidateTeam(ctx context.Context, teamID int64) error {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateTeam")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskCacheInvalidator_InvalidateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateTeam'
type MockTaskCacheInvalidator_InvalidateTeam_Call struct {
	*mock.Call
}

// InvalidateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
func (_e *MockTaskCacheInvalidator_Expecter) InvalidateTeam(ctx any, teamID any) *MockTaskCacheInvalidator_InvalidateTeam_Call {
	return &MockTaskCacheInvalidator_InvalidateTeam_Call{Call: _e.mock.On("InvalidateTeam", ctx, teamID)}
}

func (_c *MockTaskCacheInvalidator_InvalidateTeam_Call) Run(run func(ctx context.Context, teamID int64)) *MockTaskCacheInvalidator_InvalidateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskCacheInvalidator_InvalidateTeam_Call) Return(err error) *MockTaskCacheInvalidator_InvalidateTeam_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskCacheInvalidator_InvalidateTeam_Call) RunAndReturn(run func(ctx context.Context, teamID int64) error) *MockTaskCacheInvalidator_InvalidateTeam_Call {
	_c.Call.Return(run)
	return _c
}
