// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package team_list

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// ListByUser provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) ListByUser(ctx context.Context, userID int64) ([]domain.TeamWithRole, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []domain.TeamWithRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]domain.TeamWithRole, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []domain.TeamWithRole); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TeamWithRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockTeamRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockTeamRepository_Expecter) ListByUser(ctx any, userID any) *MockTeamRepository_ListByUser_Call {
	return &MockTeamRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockTeamRepository_ListByUser_Call) Run(run func(ctx context.Context, userID int64)) *MockTeamRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_ListByUser_Call) Return(teamWithRoles []domain.TeamWithRole, err error) *MockTeamRepository_ListByUser_Call {
	_c.Call.Return(teamWithRoles, err)
	return _c
}

func (_c *MockTeamRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]domain.TeamWithRole, error)) *MockTeamRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
