// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package task_list

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) List(ctx context.Context, filter domain.TaskFilter) (domain.TaskPage, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 domain.TaskPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskFilter) (domain.TaskPage, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskFilter) domain.TaskPage); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Get(0).(domain.TaskPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TaskFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTaskRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.TaskFilter
func (_e *MockTaskRepository_Expecter) List(ctx any, filter any) *MockTaskRepository_List_Call {
	return &MockTaskRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockTaskRepository_List_Call) Run(run func(ctx context.Context, filter domain.TaskFilter)) *MockTaskRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TaskFilter
		if args[1] != nil {
			arg1 = args[1].(domain.TaskFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_List_Call) Return(taskPage domain.TaskPage, err error) *MockTaskRepository_List_Call {
	_c.Call.Return(taskPage, err)
	return _c
}

func (_c *MockTaskRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter domain.TaskFilter) (domain.TaskPage, error)) *MockTaskRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamAccess creates a new instance of MockTeamAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamAccess {
	mock := &MockTeamAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamAccess is an autogenerated mock type for the TeamAccess type
type MockTeamAccess struct {
	mock.Mock
}

type MockTeamAccess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamAccess) EXPECT() *MockTeamAccess_Expecter {
	return &MockTeamAccess_Expecter{mock: &_m.Mock}
}

// EnsureTeamMember provides a mock function for the type MockTeamAccess
func (_mock *MockTeamAccess) EnsureTeamMember(ctx context.Context, teamID int64, actorID int64) error {
	ret := _mock.Called(ctx, teamID, actorID)

	if len(ret) == 0 {
		panic("no return value specified for EnsureTeamMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, teamID, actorID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamAccess_EnsureTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureTeamMember'
type MockTeamAccess_EnsureTeamMember_Call struct {
	*mock.Call
}

// EnsureTeamMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
//   - actorID int64
func (_e *MockTeamAccess_Expecter) EnsureTeamMember(ctx any, teamID any, actorID any) *MockTeamAccess_EnsureTeamMember_Call {
	return &MockTeamAccess_EnsureTeamMember_Call{Call: _e.mock.On("EnsureTeamMember", ctx, teamID, actorID)}
}

func (_c *MockTeamAccess_EnsureTeamMember_Call) Run(run func(ctx context.Context, teamID int64, actorID int64)) *MockTeamAccess_EnsureTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTeamAccess_EnsureTeamMember_Call) Return(err error) *MockTeamAccess_EnsureTeamMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamAccess_EnsureTeamMember_Call) RunAndReturn(run func(ctx context.Context, teamID int64, actorID int64) error) *MockTeamAccess_EnsureTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskListCache creates a new instance of MockTaskListCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskListCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskListCache {
	mock := &MockTaskListCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskListCache is an autogenerated mock type for the TaskListCache type
type MockTaskListCache struct {
	mock.Mock
}

type MockTaskListCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskListCache) EXPECT() *MockTaskListCache_Expecter {
	return &MockTaskListCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockTaskListCache
func (_mock *MockTaskListCache) Get(ctx context.Context, filter domain.TaskFilter) (domain.TaskPage, bool, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.TaskPage
	var r1 bool
	var r2 int64
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskFilter) (domain.TaskPage, bool, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskFilter) domain.TaskPage); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Get(0).(domain.TaskPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TaskFilter) bool); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.TaskFilter) int64); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Get(2).(int64)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, domain.TaskFilter) error); ok {
		r3 = returnFunc(ctx, filter)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockTaskListCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTaskListCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.TaskFilter
func (_e *MockTaskListCache_Expecter) Get(ctx any, filter any) *MockTaskListCache_Get_Call {
	return &MockTaskListCache_Get_Call{Call: _e.mock.On("Get", ctx, filter)}
}

func (_c *MockTaskListCache_Get_Call) Run(run func(ctx context.Context, filter domain.TaskFilter)) *MockTaskListCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TaskFilter
		if args[1] != nil {
			arg1 = args[1].(domain.TaskFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskListCache_Get_Call) Return(page domain.TaskPage, hit bool, version int64, err error) *MockTaskListCache_Get_Call {
	_c.Call.Return(page, hit, version, err)
	return _c
}

func (_c *MockTaskListCache_Get_Call) RunAndReturn(run func(ctx context.Context, filter domain.TaskFilter) (domain.TaskPage, bool, int64, error)) *MockTaskListCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockTaskListCache
func (_mock *MockTaskListCache) Set(ctx context.Context, filter domain.TaskFilter, version int64, page domain.TaskPage) error {
	ret := _mock.Called(ctx, filter, version, page)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskFilter, int64, domain.TaskPage) error); ok {
		r0 = returnFunc(ctx, filter, version, page)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskListCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockTaskListCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.TaskFilter
//   - version int64
//   - page domain.TaskPage
func (_e *MockTaskListCache_Expecter) Set(ctx any, filter any, version any, page any) *MockTaskListCache_Set_Call {
	return &MockTaskListCache_Set_Call{Call: _e.mock.On("Set", ctx, filter, version, page)}
}

func (_c *MockTaskListCache_Set_Call) Run(run func(ctx context.Context, filter domain.TaskFilter, version int64, page domain.TaskPage)) *MockTaskListCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TaskFilter
		if args[1] != nil {
			arg1 = args[1].(domain.TaskFilter)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 domain.TaskPage
		if args[3] != nil {
			arg3 = args[3].(domain.TaskPage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTaskListCache_Set_Call) Return(err error) *MockTaskListCache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskListCache_Set_Call) RunAndReturn(run func(ctx context.Context, filter domain.TaskFilter, version int64, page domain.TaskPage) error) *MockTaskListCache_Set_Call {
	_c.Call.Return(run)
	return _c
}
