// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_register

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(ctx context.Context, user domain.User) (int64, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (int64, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) int64); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockUserRepository_Expecter) Create(ctx any, user any) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, user domain.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(n int64, err error) *MockUserRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (int64, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordHasher creates a new instance of MockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordHasher {
	mock := &MockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type MockPasswordHasher struct {
	mock.Mock
}

type MockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordHasher) EXPECT() *MockPasswordHasher_Expecter {
	return &MockPasswordHasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockPasswordHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordHasher_Expecter) Hash(password any) *MockPasswordHasher_Hash_Call {
	return &MockPasswordHasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockPasswordHasher_Hash_Call) Run(run func(password string)) *MockPasswordHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordHasher_Hash_Call) Return(s string, err error) *MockPasswordHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordHasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *MockPasswordHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
