// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package team_invite

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) AddMember(ctx context.Context, member domain.TeamMember) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TeamMember) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockTeamRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - member domain.TeamMember
func (_e *MockTeamRepository_Expecter) AddMember(ctx any, member any) *MockTeamRepository_AddMember_Call {
	return &MockTeamRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, member)}
}

func (_c *MockTeamRepository_AddMember_Call) Run(run func(ctx context.Context, member domain.TeamMember)) *MockTeamRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TeamMember
		if args[1] != nil {
			arg1 = args[1].(domain.TeamMember)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_AddMember_Call) Return(err error) *MockTeamRepository_AddMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_AddMember_Call) RunAndReturn(run func(ctx context.Context, member domain.TeamMember) error) *MockTeamRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMember provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetMember(ctx context.Context, teamID int64, userID int64) (domain.TeamMember, error) {
	ret := _mock.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 domain.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (domain.TeamMember, error)); ok {
		return returnFunc(ctx, teamID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) domain.TeamMember); ok {
		r0 = returnFunc(ctx, teamID, userID)
	} else {
		r0 = ret.Get(0).(domain.TeamMember)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type MockTeamRepository_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
//   - userID int64
func (_e *MockTeamRepository_Expecter) GetMember(ctx any, teamID any, userID any) *MockTeamRepository_GetMember_Call {
	return &MockTeamRepository_GetMember_Call{Call: _e.mock.On("GetMember", ctx, teamID, userID)}
}

func (_c *MockTeamRepository_GetMember_Call) Run(run func(ctx context.Context, teamID int64, userID int64)) *MockTeamRepository_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetMember_Call) Return(teamMember domain.TeamMember, err error) *MockTeamRepository_GetMember_Call {
	_c.Call.Return(teamMember, err)
	return _c
}

func (_c *MockTeamRepository_GetMember_Call) RunAndReturn(run func(ctx context.Context, teamID int64, userID int64) (domain.TeamMember, error)) *MockTeamRepository_GetMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetTeam(ctx context.Context, teamID int64) (domain.Team, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 domain.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (domain.Team, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) domain.Team); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Get(0).(domain.Team)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockTeamRepository_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
func (_e *MockTeamRepository_Expecter) GetTeam(ctx any, teamID any) *MockTeamRepository_GetTeam_Call {
	return &MockTeamRepository_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, teamID)}
}

func (_c *MockTeamRepository_GetTeam_Call) Run(run func(ctx context.Context, teamID int64)) *MockTeamRepository_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetTeam_Call) Return(team domain.Team, err error) *MockTeamRepository_GetTeam_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepository_GetTeam_Call) RunAndReturn(run func(ctx context.Context, teamID int64) (domain.Team, error)) *MockTeamRepository_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(ctx any, email any) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(user domain.User, err error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (domain.User, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInviteNotifier creates a new instance of MockInviteNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInviteNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInviteNotifier {
	mock := &MockInviteNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInviteNotifier is an autogenerated mock type for the InviteNotifier type
type MockInviteNotifier struct {
	mock.Mock
}

type MockInviteNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInviteNotifier) EXPECT() *MockInviteNotifier_Expecter {
	return &MockInviteNotifier_Expecter{mock: &_m.Mock}
}

// SendInvite provides a mock function for the type MockInviteNotifier
func (_mock *MockInviteNotifier) SendInvite(ctx context.Context, email string, teamName string) error {
	ret := _mock.Called(ctx, email, teamName)

	if len(ret) == 0 {
		panic("no return value specified for SendInvite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, teamName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInviteNotifier_SendInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendInvite'
type MockInviteNotifier_SendInvite_Call struct {
	*mock.Call
}

// SendInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - teamName string
func (_e *MockInviteNotifier_Expecter) SendInvite(ctx any, email any, teamName any) *MockInviteNotifier_SendInvite_Call {
	return &MockInviteNotifier_SendInvite_Call{Call: _e.mock.On("SendInvite", ctx, email, teamName)}
}

func (_c *MockInviteNotifier_SendInvite_Call) Run(run func(ctx context.Context, email string, teamName string)) *MockInviteNotifier_SendInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInviteNotifier_SendInvite_Call) Return(err error) *MockInviteNotifier_SendInvite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInviteNotifier_SendInvite_Call) RunAndReturn(run func(ctx context.Context, email string, teamName string) error) *MockInviteNotifier_SendInvite_Call {
	_c.Call.Return(run)
	return _c
}
