// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package taskaccess

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskGetter creates a new instance of MockTaskGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskGetter {
	mock := &MockTaskGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskGetter is an autogenerated mock type for the TaskGetter type
type MockTaskGetter struct {
	mock.Mock
}

type MockTaskGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskGetter) EXPECT() *MockTaskGetter_Expecter {
	return &MockTaskGetter_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockTaskGetter
func (_mock *MockTaskGetter) GetByID(ctx context.Context, taskID int64) (domain.Task, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (domain.Task, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) domain.Task); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskGetter_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTaskGetter_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int64
func (_e *MockTaskGetter_Expecter) GetByID(ctx any, taskID any) *MockTaskGetter_GetByID_Call {
	return &MockTaskGetter_GetByID_Call{Call: _e.mock.On("GetByID", ctx, taskID)}
}

func (_c *MockTaskGetter_GetByID_Call) Run(run func(ctx context.Context, taskID int64)) *MockTaskGetter_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskGetter_GetByID_Call) Return(task domain.Task, err error) *MockTaskGetter_GetByID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskGetter_GetByID_Call) RunAndReturn(run func(ctx context.Context, taskID int64) (domain.Task, error)) *MockTaskGetter_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemberGetter creates a new instance of MockMemberGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemberGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemberGetter {
	mock := &MockMemberGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMemberGetter is an autogenerated mock type for the MemberGetter type
type MockMemberGetter struct {
	mock.Mock
}

type MockMemberGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemberGetter) EXPECT() *MockMemberGetter_Expecter {
	return &MockMemberGetter_Expecter{mock: &_m.Mock}
}

// GetMember provides a mock function for the type MockMemberGetter
func (_mock *MockMemberGetter) GetMember(ctx context.Context, teamID int64, userID int64) (domain.TeamMember, error) {
	ret := _mock.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 domain.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (domain.TeamMember, error)); ok {
		return returnFunc(ctx, teamID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) domain.TeamMember); ok {
		r0 = returnFunc(ctx, teamID, userID)
	} else {
		r0 = ret.Get(0).(domain.TeamMember)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMemberGetter_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type MockMemberGetter_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int64
//   - userID int64
func (_e *MockMemberGetter_Expecter) GetMember(ctx any, teamID any, userID any) *MockMemberGetter_GetMember_Call {
	return &MockMemberGetter_GetMember_Call{Call: _e.mock.On("GetMember", ctx, teamID, userID)}
}

func (_c *MockMemberGetter_GetMember_Call) Run(run func(ctx context.Context, teamID int64, userID int64)) *MockMemberGetter_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMemberGetter_GetMember_Call) Return(teamMember domain.TeamMember, err error) *MockMemberGetter_GetMember_Call {
	_c.Call.Return(teamMember, err)
	return _c
}

func (_c *MockMemberGetter_GetMember_Call) RunAndReturn(run func(ctx context.Context, teamID int64, userID int64) (domain.TeamMember, error)) *MockMemberGetter_GetMember_Call {
	_c.Call.Return(run)
	return _c
}
