// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"
	"team-taskflow/internal/domain"
	"team-taskflow/internal/usecase/auth_login"
	"team-taskflow/internal/usecase/auth_register"
	"team-taskflow/internal/usecase/comment_create"
	"team-taskflow/internal/usecase/comment_list"
	"team-taskflow/internal/usecase/task_create"
	"team-taskflow/internal/usecase/task_history_get"
	"team-taskflow/internal/usecase/task_list"
	"team-taskflow/internal/usecase/task_update"
	"team-taskflow/internal/usecase/team_create"
	"team-taskflow/internal/usecase/team_invite"
	"team-taskflow/internal/usecase/team_list"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newMockanalyticsUsecase creates a new instance of mockanalyticsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockanalyticsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockanalyticsUsecase {
	mock := &mockanalyticsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockanalyticsUsecase is an autogenerated mock type for the analyticsUsecase type
type mockanalyticsUsecase struct {
	mock.Mock
}

type mockanalyticsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockanalyticsUsecase) EXPECT() *mockanalyticsUsecase_Expecter {
	return &mockanalyticsUsecase_Expecter{mock: &_m.Mock}
}

// OrphanedAssignees provides a mock function for the type mockanalyticsUsecase
func (_mock *mockanalyticsUsecase) OrphanedAssignees(ctx context.Context, actorID int64) ([]domain.OrphanedAssigneeTask, error) {
	ret := _mock.Called(ctx, actorID)

	if len(ret) == 0 {
		panic("no return value specified for OrphanedAssignees")
	}

	var r0 []domain.OrphanedAssigneeTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]domain.OrphanedAssigneeTask, error)); ok {
		return returnFunc(ctx, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []domain.OrphanedAssigneeTask); ok {
		r0 = returnFunc(ctx, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OrphanedAssigneeTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockanalyticsUsecase_OrphanedAssignees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrphanedAssignees'
type mockanalyticsUsecase_OrphanedAssignees_Call struct {
	*mock.Call
}

// OrphanedAssignees is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID int64
func (_e *mockanalyticsUsecase_Expecter) OrphanedAssignees(ctx any, actorID any) *mockanalyticsUsecase_OrphanedAssignees_Call {
	return &mockanalyticsUsecase_OrphanedAssignees_Call{Call: _e.mock.On("OrphanedAssignees", ctx, actorID)}
}

func (_c *mockanalyticsUsecase_OrphanedAssignees_Call) Run(run func(ctx context.Context, actorID int64)) *mockanalyticsUsecase_OrphanedAssignees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockanalyticsUsecase_OrphanedAssignees_Call) Return(orphanedAssigneeTasks []domain.OrphanedAssigneeTask, err error) *mockanalyticsUsecase_OrphanedAssignees_Call {
	_c.Call.Return(orphanedAssigneeTasks, err)
	return _c
}

func (_c *mockanalyticsUsecase_OrphanedAssignees_Call) RunAndReturn(run func(ctx context.Context, actorID int64) ([]domain.OrphanedAssigneeTask, error)) *mockanalyticsUsecase_OrphanedAssignees_Call {
	_c.Call.Return(run)
	return _c
}

// TeamStats provides a mock function for the type mockanalyticsUsecase
func (_mock *mockanalyticsUsecase) TeamStats(ctx context.Context, actorID int64) ([]domain.TeamStats, error) {
	ret := _mock.Called(ctx, actorID)

	if len(ret) == 0 {
		panic("no return value specified for TeamStats")
	}

	var r0 []domain.TeamStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]domain.TeamStats, error)); ok {
		return returnFunc(ctx, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []domain.TeamStats); ok {
		r0 = returnFunc(ctx, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TeamStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockanalyticsUsecase_TeamStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamStats'
type mockanalyticsUsecase_TeamStats_Call struct {
	*mock.Call
}

// TeamStats is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID int64
func (_e *mockanalyticsUsecase_Expecter) TeamStats(ctx any, actorID any) *mockanalyticsUsecase_TeamStats_Call {
	return &mockanalyticsUsecase_TeamStats_Call{Call: _e.mock.On("TeamStats", ctx, actorID)}
}

func (_c *mockanalyticsUsecase_TeamStats_Call) Run(run func(ctx context.Context, actorID int64)) *mockanalyticsUsecase_TeamStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockanalyticsUsecase_TeamStats_Call) Return(teamStatss []domain.TeamStats, err error) *mockanalyticsUsecase_TeamStats_Call {
	_c.Call.Return(teamStatss, err)
	return _c
}

func (_c *mockanalyticsUsecase_TeamStats_Call) RunAndReturn(run func(ctx context.Context, actorID int64) ([]domain.TeamStats, error)) *mockanalyticsUsecase_TeamStats_Call {
	_c.Call.Return(run)
	return _c
}

// TopCreators provides a mock function for the type mockanalyticsUsecase
func (_mock *mockanalyticsUsecase) TopCreators(ctx context.Context, actorID int64) ([]domain.TeamTopCreator, error) {
	ret := _mock.Called(ctx, actorID)

	if len(ret) == 0 {
		panic("no return value specified for TopCreators")
	}

	var r0 []domain.TeamTopCreator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]domain.TeamTopCreator, error)); ok {
		return returnFunc(ctx, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []domain.TeamTopCreator); ok {
		r0 = returnFunc(ctx, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TeamTopCreator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockanalyticsUsecase_TopCreators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopCreators'
type mockanalyticsUsecase_TopCreators_Call struct {
	*mock.Call
}

// TopCreators is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID int64
func (_e *mockanalyticsUsecase_Expecter) TopCreators(ctx any, actorID any) *mockanalyticsUsecase_TopCreators_Call {
	return &mockanalyticsUsecase_TopCreators_Call{Call: _e.mock.On("TopCreators", ctx, actorID)}
}

func (_c *mockanalyticsUsecase_TopCreators_Call) Run(run func(ctx context.Context, actorID int64)) *mockanalyticsUsecase_TopCreators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockanalyticsUsecase_TopCreators_Call) Return(teamTopCreators []domain.TeamTopCreator, err error) *mockanalyticsUsecase_TopCreators_Call {
	_c.Call.Return(teamTopCreators, err)
	return _c
}

func (_c *mockanalyticsUsecase_TopCreators_Call) RunAndReturn(run func(ctx context.Context, actorID int64) ([]domain.TeamTopCreator, error)) *mockanalyticsUsecase_TopCreators_Call {
	_c.Call.Return(run)
	return _c
}

// newMockloginUsecase creates a new instance of mockloginUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockloginUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockloginUsecase {
	mock := &mockloginUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockloginUsecase is an autogenerated mock type for the loginUsecase type
type mockloginUsecase struct {
	mock.Mock
}

type mockloginUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockloginUsecase) EXPECT() *mockloginUsecase_Expecter {
	return &mockloginUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mockloginUsecase
func (_mock *mockloginUsecase) Handle(ctx context.Context, in auth_login.Input) (auth_login.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 auth_login.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth_login.Input) (auth_login.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth_login.Input) auth_login.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(auth_login.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth_login.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockloginUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockloginUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in auth_login.Input
func (_e *mockloginUsecase_Expecter) Handle(ctx any, in any) *mockloginUsecase_Handle_Call {
	return &mockloginUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mockloginUsecase_Handle_Call) Run(run func(ctx context.Context, in auth_login.Input)) *mockloginUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth_login.Input
		if args[1] != nil {
			arg1 = args[1].(auth_login.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockloginUsecase_Handle_Call) Return(output auth_login.Output, err error) *mockloginUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mockloginUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in auth_login.Input) (auth_login.Output, error)) *mockloginUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockregisterUsecase creates a new instance of mockregisterUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockregisterUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockregisterUsecase {
	mock := &mockregisterUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockregisterUsecase is an autogenerated mock type for the registerUsecase type
type mockregisterUsecase struct {
	mock.Mock
}

type mockregisterUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockregisterUsecase) EXPECT() *mockregisterUsecase_Expecter {
	return &mockregisterUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mockregisterUsecase
func (_mock *mockregisterUsecase) Handle(ctx context.Context, in auth_register.Input) (auth_register.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 auth_register.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth_register.Input) (auth_register.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth_register.Input) auth_register.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(auth_register.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth_register.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockregisterUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockregisterUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in auth_register.Input
func (_e *mockregisterUsecase_Expecter) Handle(ctx any, in any) *mockregisterUsecase_Handle_Call {
	return &mockregisterUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mockregisterUsecase_Handle_Call) Run(run func(ctx context.Context, in auth_register.Input)) *mockregisterUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth_register.Input
		if args[1] != nil {
			arg1 = args[1].(auth_register.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockregisterUsecase_Handle_Call) Return(output auth_register.Output, err error) *mockregisterUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mockregisterUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in auth_register.Input) (auth_register.Output, error)) *mockregisterUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockcommentCreateUsecase creates a new instance of mockcommentCreateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcommentCreateUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcommentCreateUsecase {
	mock := &mockcommentCreateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcommentCreateUsecase is an autogenerated mock type for the commentCreateUsecase type
type mockcommentCreateUsecase struct {
	mock.Mock
}

type mockcommentCreateUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcommentCreateUsecase) EXPECT() *mockcommentCreateUsecase_Expecter {
	return &mockcommentCreateUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mockcommentCreateUsecase
func (_mock *mockcommentCreateUsecase) Handle(ctx context.Context, in comment_create.Input) (comment_create.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 comment_create.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, comment_create.Input) (comment_create.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, comment_create.Input) comment_create.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(comment_create.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, comment_create.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcommentCreateUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockcommentCreateUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in comment_create.Input
func (_e *mockcommentCreateUsecase_Expecter) Handle(ctx any, in any) *mockcommentCreateUsecase_Handle_Call {
	return &mockcommentCreateUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mockcommentCreateUsecase_Handle_Call) Run(run func(ctx context.Context, in comment_create.Input)) *mockcommentCreateUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 comment_create.Input
		if args[1] != nil {
			arg1 = args[1].(comment_create.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockcommentCreateUsecase_Handle_Call) Return(output comment_create.Output, err error) *mockcommentCreateUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mockcommentCreateUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in comment_create.Input) (comment_create.Output, error)) *mockcommentCreateUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockcommentListUsecase creates a new instance of mockcommentListUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcommentListUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcommentListUsecase {
	mock := &mockcommentListUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcommentListUsecase is an autogenerated mock type for the commentListUsecase type
type mockcommentListUsecase struct {
	mock.Mock
}

type mockcommentListUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcommentListUsecase) EXPECT() *mockcommentListUsecase_Expecter {
	return &mockcommentListUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mockcommentListUsecase
func (_mock *mockcommentListUsecase) Handle(ctx context.Context, in comment_list.Input) (comment_list.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 comment_list.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, comment_list.Input) (comment_list.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, comment_list.Input) comment_list.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(comment_list.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, comment_list.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcommentListUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockcommentListUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in comment_list.Input
func (_e *mockcommentListUsecase_Expecter) Handle(ctx any, in any) *mockcommentListUsecase_Handle_Call {
	return &mockcommentListUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mockcommentListUsecase_Handle_Call) Run(run func(ctx context.Context, in comment_list.Input)) *mockcommentListUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 comment_list.Input
		if args[1] != nil {
			arg1 = args[1].(comment_list.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockcommentListUsecase_Handle_Call) Return(output comment_list.Output, err error) *mockcommentListUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mockcommentListUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in comment_list.Input) (comment_list.Output, error)) *mockcommentListUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktokenParser creates a new instance of mocktokenParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktokenParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktokenParser {
	mock := &mocktokenParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktokenParser is an autogenerated mock type for the tokenParser type
type mocktokenParser struct {
	mock.Mock
}

type mocktokenParser_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktokenParser) EXPECT() *mocktokenParser_Expecter {
	return &mocktokenParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type mocktokenParser
func (_mock *mocktokenParser) Parse(token string) (int64, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktokenParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type mocktokenParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - token string
func (_e *mocktokenParser_Expecter) Parse(token any) *mocktokenParser_Parse_Call {
	return &mocktokenParser_Parse_Call{Call: _e.mock.On("Parse", token)}
}

func (_c *mocktokenParser_Parse_Call) Run(run func(token string)) *mocktokenParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocktokenParser_Parse_Call) Return(n int64, err error) *mocktokenParser_Parse_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mocktokenParser_Parse_Call) RunAndReturn(run func(token string) (int64, error)) *mocktokenParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// newMockhttpMetrics creates a new instance of mockhttpMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhttpMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhttpMetrics {
	mock := &mockhttpMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockhttpMetrics is an autogenerated mock type for the httpMetrics type
type mockhttpMetrics struct {
	mock.Mock
}

type mockhttpMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhttpMetrics) EXPECT() *mockhttpMetrics_Expecter {
	return &mockhttpMetrics_Expecter{mock: &_m.Mock}
}

// Observe provides a mock function for the type mockhttpMetrics
func (_mock *mockhttpMetrics) Observe(method string, path string, status int, elapsed time.Duration) {
	_mock.Called(method, path, status, elapsed)
	return
}

// mockhttpMetrics_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type mockhttpMetrics_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - method string
//   - path string
//   - status int
//   - elapsed time.Duration
func (_e *mockhttpMetrics_Expecter) Observe(method any, path any, status any, elapsed any) *mockhttpMetrics_Observe_Call {
	return &mockhttpMetrics_Observe_Call{Call: _e.mock.On("Observe", method, path, status, elapsed)}
}

func (_c *mockhttpMetrics_Observe_Call) Run(run func(method string, path string, status int, elapsed time.Duration)) *mockhttpMetrics_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockhttpMetrics_Observe_Call) Return() *mockhttpMetrics_Observe_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockhttpMetrics_Observe_Call) RunAndReturn(run func(method string, path string, status int, elapsed time.Duration)) *mockhttpMetrics_Observe_Call {
	_c.Run(run)
	return _c
}

// newMockrateLimiter creates a new instance of mockrateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockrateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockrateLimiter {
	mock := &mockrateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockrateLimiter is an autogenerated mock type for the rateLimiter type
type mockrateLimiter struct {
	mock.Mock
}

type mockrateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockrateLimiter) EXPECT() *mockrateLimiter_Expecter {
	return &mockrateLimiter_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function for the type mockrateLimiter
func (_mock *mockrateLimiter) Allow(ctx context.Context, key string) (bool, time.Duration, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 bool
	var r1 time.Duration
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, time.Duration, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) time.Duration); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockrateLimiter_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type mockrateLimiter_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *mockrateLimiter_Expecter) Allow(ctx any, key any) *mockrateLimiter_Allow_Call {
	return &mockrateLimiter_Allow_Call{Call: _e.mock.On("Allow", ctx, key)}
}

func (_c *mockrateLimiter_Allow_Call) Run(run func(ctx context.Context, key string)) *mockrateLimiter_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrateLimiter_Allow_Call) Return(allowed bool, retryAfter time.Duration, err error) *mockrateLimiter_Allow_Call {
	_c.Call.Return(allowed, retryAfter, err)
	return _c
}

func (_c *mockrateLimiter_Allow_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, time.Duration, error)) *mockrateLimiter_Allow_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktaskCreateUsecase creates a new instance of mocktaskCreateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktaskCreateUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktaskCreateUsecase {
	mock := &mocktaskCreateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktaskCreateUsecase is an autogenerated mock type for the taskCreateUsecase type
type mocktaskCreateUsecase struct {
	mock.Mock
}

type mocktaskCreateUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktaskCreateUsecase) EXPECT() *mocktaskCreateUsecase_Expecter {
	return &mocktaskCreateUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mocktaskCreateUsecase
func (_mock *mocktaskCreateUsecase) Handle(ctx context.Context, in task_create.Input) (task_create.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 task_create.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task_create.Input) (task_create.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, task_create.Input) task_create.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(task_create.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, task_create.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktaskCreateUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mocktaskCreateUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in task_create.Input
func (_e *mocktaskCreateUsecase_Expecter) Handle(ctx any, in any) *mocktaskCreateUsecase_Handle_Call {
	return &mocktaskCreateUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mocktaskCreateUsecase_Handle_Call) Run(run func(ctx context.Context, in task_create.Input)) *mocktaskCreateUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task_create.Input
		if args[1] != nil {
			arg1 = args[1].(task_create.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktaskCreateUsecase_Handle_Call) Return(output task_create.Output, err error) *mocktaskCreateUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mocktaskCreateUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in task_create.Input) (task_create.Output, error)) *mocktaskCreateUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktaskHistoryUsecase creates a new instance of mocktaskHistoryUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktaskHistoryUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktaskHistoryUsecase {
	mock := &mocktaskHistoryUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktaskHistoryUsecase is an autogenerated mock type for the taskHistoryUsecase type
type mocktaskHistoryUsecase struct {
	mock.Mock
}

type mocktaskHistoryUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktaskHistoryUsecase) EXPECT() *mocktaskHistoryUsecase_Expecter {
	return &mocktaskHistoryUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mocktaskHistoryUsecase
func (_mock *mocktaskHistoryUsecase) Handle(ctx context.Context, in task_history_get.Input) (task_history_get.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 task_history_get.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task_history_get.Input) (task_history_get.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, task_history_get.Input) task_history_get.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(task_history_get.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, task_history_get.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktaskHistoryUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mocktaskHistoryUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in task_history_get.Input
func (_e *mocktaskHistoryUsecase_Expecter) Handle(ctx any, in any) *mocktaskHistoryUsecase_Handle_Call {
	return &mocktaskHistoryUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mocktaskHistoryUsecase_Handle_Call) Run(run func(ctx context.Context, in task_history_get.Input)) *mocktaskHistoryUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task_history_get.Input
		if args[1] != nil {
			arg1 = args[1].(task_history_get.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktaskHistoryUsecase_Handle_Call) Return(output task_history_get.Output, err error) *mocktaskHistoryUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mocktaskHistoryUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in task_history_get.Input) (task_history_get.Output, error)) *mocktaskHistoryUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktaskListUsecase creates a new instance of mocktaskListUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktaskListUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktaskListUsecase {
	mock := &mocktaskListUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktaskListUsecase is an autogenerated mock type for the taskListUsecase type
type mocktaskListUsecase struct {
	mock.Mock
}

type mocktaskListUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktaskListUsecase) EXPECT() *mocktaskListUsecase_Expecter {
	return &mocktaskListUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mocktaskListUsecase
func (_mock *mocktaskListUsecase) Handle(ctx context.Context, in task_list.Input) (task_list.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 task_list.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task_list.Input) (task_list.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, task_list.Input) task_list.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(task_list.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, task_list.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktaskListUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mocktaskListUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in task_list.Input
func (_e *mocktaskListUsecase_Expecter) Handle(ctx any, in any) *mocktaskListUsecase_Handle_Call {
	return &mocktaskListUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mocktaskListUsecase_Handle_Call) Run(run func(ctx context.Context, in task_list.Input)) *mocktaskListUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task_list.Input
		if args[1] != nil {
			arg1 = args[1].(task_list.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktaskListUsecase_Handle_Call) Return(output task_list.Output, err error) *mocktaskListUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mocktaskListUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in task_list.Input) (task_list.Output, error)) *mocktaskListUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktaskUpdateUsecase creates a new instance of mocktaskUpdateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktaskUpdateUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktaskUpdateUsecase {
	mock := &mocktaskUpdateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktaskUpdateUsecase is an autogenerated mock type for the taskUpdateUsecase type
type mocktaskUpdateUsecase struct {
	mock.Mock
}

type mocktaskUpdateUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktaskUpdateUsecase) EXPECT() *mocktaskUpdateUsecase_Expecter {
	return &mocktaskUpdateUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mocktaskUpdateUsecase
func (_mock *mocktaskUpdateUsecase) Handle(ctx context.Context, in task_update.Input) (task_update.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 task_update.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task_update.Input) (task_update.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, task_update.Input) task_update.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(task_update.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, task_update.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktaskUpdateUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mocktaskUpdateUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in task_update.Input
func (_e *mocktaskUpdateUsecase_Expecter) Handle(ctx any, in any) *mocktaskUpdateUsecase_Handle_Call {
	return &mocktaskUpdateUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mocktaskUpdateUsecase_Handle_Call) Run(run func(ctx context.Context, in task_update.Input)) *mocktaskUpdateUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task_update.Input
		if args[1] != nil {
			arg1 = args[1].(task_update.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktaskUpdateUsecase_Handle_Call) Return(output task_update.Output, err error) *mocktaskUpdateUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mocktaskUpdateUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in task_update.Input) (task_update.Output, error)) *mocktaskUpdateUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockteamCreateUsecase creates a new instance of mockteamCreateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockteamCreateUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockteamCreateUsecase {
	mock := &mockteamCreateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockteamCreateUsecase is an autogenerated mock type for the teamCreateUsecase type
type mockteamCreateUsecase struct {
	mock.Mock
}

type mockteamCreateUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockteamCreateUsecase) EXPECT() *mockteamCreateUsecase_Expecter {
	return &mockteamCreateUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mockteamCreateUsecase
func (_mock *mockteamCreateUsecase) Handle(ctx context.Context, in team_create.Input) (team_create.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 team_create.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, team_create.Input) (team_create.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, team_create.Input) team_create.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(team_create.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, team_create.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockteamCreateUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockteamCreateUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in team_create.Input
func (_e *mockteamCreateUsecase_Expecter) Handle(ctx any, in any) *mockteamCreateUsecase_Handle_Call {
	return &mockteamCreateUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mockteamCreateUsecase_Handle_Call) Run(run func(ctx context.Context, in team_create.Input)) *mockteamCreateUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 team_create.Input
		if args[1] != nil {
			arg1 = args[1].(team_create.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockteamCreateUsecase_Handle_Call) Return(output team_create.Output, err error) *mockteamCreateUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mockteamCreateUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in team_create.Input) (team_create.Output, error)) *mockteamCreateUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockteamInviteUsecase creates a new instance of mockteamInviteUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockteamInviteUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockteamInviteUsecase {
	mock := &mockteamInviteUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockteamInviteUsecase is an autogenerated mock type for the teamInviteUsecase type
type mockteamInviteUsecase struct {
	mock.Mock
}

type mockteamInviteUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockteamInviteUsecase) EXPECT() *mockteamInviteUsecase_Expecter {
	return &mockteamInviteUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mockteamInviteUsecase
func (_mock *mockteamInviteUsecase) Handle(ctx context.Context, in team_invite.Input) (team_invite.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 team_invite.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, team_invite.Input) (team_invite.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, team_invite.Input) team_invite.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(team_invite.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, team_invite.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockteamInviteUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockteamInviteUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in team_invite.Input
func (_e *mockteamInviteUsecase_Expecter) Handle(ctx any, in any) *mockteamInviteUsecase_Handle_Call {
	return &mockteamInviteUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mockteamInviteUsecase_Handle_Call) Run(run func(ctx context.Context, in team_invite.Input)) *mockteamInviteUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 team_invite.Input
		if args[1] != nil {
			arg1 = args[1].(team_invite.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockteamInviteUsecase_Handle_Call) Return(output team_invite.Output, err error) *mockteamInviteUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mockteamInviteUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in team_invite.Input) (team_invite.Output, error)) *mockteamInviteUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockteamListUsecase creates a new instance of mockteamListUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockteamListUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockteamListUsecase {
	mock := &mockteamListUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockteamListUsecase is an autogenerated mock type for the teamListUsecase type
type mockteamListUsecase struct {
	mock.Mock
}

type mockteamListUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockteamListUsecase) EXPECT() *mockteamListUsecase_Expecter {
	return &mockteamListUsecase_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type mockteamListUsecase
func (_mock *mockteamListUsecase) Handle(ctx context.Context, in team_list.Input) (team_list.Output, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 team_list.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, team_list.Input) (team_list.Output, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, team_list.Input) team_list.Output); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(team_list.Output)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, team_list.Input) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockteamListUsecase_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockteamListUsecase_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in team_list.Input
func (_e *mockteamListUsecase_Expecter) Handle(ctx any, in any) *mockteamListUsecase_Handle_Call {
	return &mockteamListUsecase_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *mockteamListUsecase_Handle_Call) Run(run func(ctx context.Context, in team_list.Input)) *mockteamListUsecase_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 team_list.Input
		if args[1] != nil {
			arg1 = args[1].(team_list.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockteamListUsecase_Handle_Call) Return(output team_list.Output, err error) *mockteamListUsecase_Handle_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *mockteamListUsecase_Handle_Call) RunAndReturn(run func(ctx context.Context, in team_list.Input) (team_list.Output, error)) *mockteamListUsecase_Handle_Call {
	_c.Call.Return(run)
	return _c
}
