// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package team_create

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) AddMember(ctx context.Context, member domain.TeamMember) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TeamMember) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockTeamRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - member domain.TeamMember
func (_e *MockTeamRepository_Expecter) AddMember(ctx any, member any) *MockTeamRepository_AddMember_Call {
	return &MockTeamRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, member)}
}

func (_c *MockTeamRepository_AddMember_Call) Run(run func(ctx context.Context, member domain.TeamMember)) *MockTeamRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TeamMember
		if args[1] != nil {
			arg1 = args[1].(domain.TeamMember)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_AddMember_Call) Return(err error) *MockTeamRepository_AddMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_AddMember_Call) RunAndReturn(run func(ctx context.Context, member domain.TeamMember) error) *MockTeamRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTeam provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) CreateTeam(ctx context.Context, team domain.Team) (int64, error) {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Team) (int64, error)); ok {
		return returnFunc(ctx, team)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Team) int64); ok {
		r0 = returnFunc(ctx, team)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Team) error); ok {
		r1 = returnFunc(ctx, team)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockTeamRepository_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - team domain.Team
func (_e *MockTeamRepository_Expecter) CreateTeam(ctx any, team any) *MockTeamRepository_CreateTeam_Call {
	return &MockTeamRepository_CreateTeam_Call{Call: _e.mock.On("CreateTeam", ctx, team)}
}

func (_c *MockTeamRepository_CreateTeam_Call) Run(run func(ctx context.Context, team domain.Team)) *MockTeamRepository_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Team
		if args[1] != nil {
			arg1 = args[1].(domain.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_CreateTeam_Call) Return(n int64, err error) *MockTeamRepository_CreateTeam_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTeamRepository_CreateTeam_Call) RunAndReturn(run func(ctx context.Context, team domain.Team) (int64, error)) *MockTeamRepository_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxManager creates a new instance of MockTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxManager {
	mock := &MockTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager struct {
	mock.Mock
}

type MockTxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxManager) EXPECT() *MockTxManager_Expecter {
	return &MockTxManager_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockTxManager
func (_mock *MockTxManager) Do(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxManager_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockTxManager_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTxManager_Expecter) Do(ctx any, fn any) *MockTxManager_Do_Call {
	return &MockTxManager_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *MockTxManager_Do_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTxManager_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxManager_Do_Call) Return(err error) *MockTxManager_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxManager_Do_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTxManager_Do_Call {
	_c.Call.Return(run)
	return _c
}
