// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package comment_create

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskAccess creates a new instance of MockTaskAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskAccess {
	mock := &MockTaskAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskAccess is an autogenerated mock type for the TaskAccess type
type MockTaskAccess struct {
	mock.Mock
}

type MockTaskAccess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskAccess) EXPECT() *MockTaskAccess_Expecter {
	return &MockTaskAccess_Expecter{mock: &_m.Mock}
}

// LoadTaskForMember provides a mock function for the type MockTaskAccess
func (_mock *MockTaskAccess) LoadTaskForMember(ctx context.Context, taskID int64, actorID int64) (domain.Task, error) {
	ret := _mock.Called(ctx, taskID, actorID)

	if len(ret) == 0 {
		panic("no return value specified for LoadTaskForMember")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (domain.Task, error)); ok {
		return returnFunc(ctx, taskID, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) domain.Task); ok {
		r0 = returnFunc(ctx, taskID, actorID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, taskID, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskAccess_LoadTaskForMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadTaskForMember'
type MockTaskAccess_LoadTaskForMember_Call struct {
	*mock.Call
}

// LoadTaskForMember is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int64
//   - actorID int64
func (_e *MockTaskAccess_Expecter) LoadTaskForMember(ctx any, taskID any, actorID any) *MockTaskAccess_LoadTaskForMember_Call {
	return &MockTaskAccess_LoadTaskForMember_Call{Call: _e.mock.On("LoadTaskForMember", ctx, taskID, actorID)}
}

func (_c *MockTaskAccess_LoadTaskForMember_Call) Run(run func(ctx context.Context, taskID int64, actorID int64)) *MockTaskAccess_LoadTaskForMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskAccess_LoadTaskForMember_Call) Return(task domain.Task, err error) *MockTaskAccess_LoadTaskForMember_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskAccess_LoadTaskForMember_Call) RunAndReturn(run func(ctx context.Context, taskID int64, actorID int64) (domain.Task, error)) *MockTaskAccess_LoadTaskForMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommentRepository creates a new instance of MockCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentRepository {
	mock := &MockCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommentRepository is an autogenerated mock type for the CommentRepository type
type MockCommentRepository struct {
	mock.Mock
}

type MockCommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentRepository) EXPECT() *MockCommentRepository_Expecter {
	return &MockCommentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) Create(ctx context.Context, comment domain.TaskComment) (int64, error) {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskComment) (int64, error)); ok {
		return returnFunc(ctx, comment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.TaskComment) int64); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.TaskComment) error); ok {
		r1 = returnFunc(ctx, comment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - comment domain.TaskComment
func (_e *MockCommentRepository_Expecter) Create(ctx any, comment any) *MockCommentRepository_Create_Call {
	return &MockCommentRepository_Create_Call{Call: _e.mock.On("Create", ctx, comment)}
}

func (_c *MockCommentRepository_Create_Call) Run(run func(ctx context.Context, comment domain.TaskComment)) *MockCommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.TaskComment
		if args[1] != nil {
			arg1 = args[1].(domain.TaskComment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_Create_Call) Return(n int64, err error) *MockCommentRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCommentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, comment domain.TaskComment) (int64, error)) *MockCommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) GetByID(ctx context.Context, commentID int64) (domain.TaskComment, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.TaskComment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (domain.TaskComment, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) domain.TaskComment); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		r0 = ret.Get(0).(domain.TaskComment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCommentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID int64
func (_e *MockCommentRepository_Expecter) GetByID(ctx any, commentID any) *MockCommentRepository_GetByID_Call {
	return &MockCommentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, commentID)}
}

func (_c *MockCommentRepository_GetByID_Call) Run(run func(ctx context.Context, commentID int64)) *MockCommentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_GetByID_Call) Return(taskComment domain.TaskComment, err error) *MockCommentRepository_GetByID_Call {
	_c.Call.Return(taskComment, err)
	return _c
}

func (_c *MockCommentRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, commentID int64) (domain.TaskComment, error)) *MockCommentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
