// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package analytics_get

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalyticsRepository creates a new instance of MockAnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type MockAnalyticsRepository struct {
	mock.Mock
}

type MockAnalyticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepository_Expecter {
	return &MockAnalyticsRepository_Expecter{mock: &_m.Mock}
}

// OrphanedAssignees provides a mock function for the type MockAnalyticsRepository
func (_mock *MockAnalyticsRepository) OrphanedAssignees(ctx context.Context, actorID int64) ([]domain.OrphanedAssigneeTask, error) {
	ret := _mock.Called(ctx, actorID)

	if len(ret) == 0 {
		panic("no return value specified for OrphanedAssignees")
	}

	var r0 []domain.OrphanedAssigneeTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]domain.OrphanedAssigneeTask, error)); ok {
		return returnFunc(ctx, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []domain.OrphanedAssigneeTask); ok {
		r0 = returnFunc(ctx, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OrphanedAssigneeTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsRepository_OrphanedAssignees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrphanedAssignees'
type MockAnalyticsRepository_OrphanedAssignees_Call struct {
	*mock.Call
}

// OrphanedAssignees is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID int64
func (_e *MockAnalyticsRepository_Expecter) OrphanedAssignees(ctx any, actorID any) *MockAnalyticsRepository_OrphanedAssignees_Call {
	return &MockAnalyticsRepository_OrphanedAssignees_Call{Call: _e.mock.On("OrphanedAssignees", ctx, actorID)}
}

func (_c *MockAnalyticsRepository_OrphanedAssignees_Call) Run(run func(ctx context.Context, actorID int64)) *MockAnalyticsRepository_OrphanedAssignees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsRepository_OrphanedAssignees_Call) Return(orphanedAssigneeTasks []domain.OrphanedAssigneeTask, err error) *MockAnalyticsRepository_OrphanedAssignees_Call {
	_c.Call.Return(orphanedAssigneeTasks, err)
	return _c
}

func (_c *MockAnalyticsRepository_OrphanedAssignees_Call) RunAndReturn(run func(ctx context.Context, actorID int64) ([]domain.OrphanedAssigneeTask, error)) *MockAnalyticsRepository_OrphanedAssignees_Call {
	_c.Call.Return(run)
	return _c
}

// TeamStats provides a mock function for the type MockAnalyticsRepository
func (_mock *MockAnalyticsRepository) TeamStats(ctx context.Context, actorID int64, doneWindowDays int) ([]domain.TeamStats, error) {
	ret := _mock.Called(ctx, actorID, doneWindowDays)

	if len(ret) == 0 {
		panic("no return value specified for TeamStats")
	}

	var r0 []domain.TeamStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) ([]domain.TeamStats, error)); ok {
		return returnFunc(ctx, actorID, doneWindowDays)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) []domain.TeamStats); ok {
		r0 = returnFunc(ctx, actorID, doneWindowDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TeamStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = returnFunc(ctx, actorID, doneWindowDays)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsRepository_TeamStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeamStats'
type MockAnalyticsRepository_TeamStats_Call struct {
	*mock.Call
}

// TeamStats is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID int64
//   - doneWindowDays int
func (_e *MockAnalyticsRepository_Expecter) TeamStats(ctx any, actorID any, doneWindowDays any) *MockAnalyticsRepository_TeamStats_Call {
	return &MockAnalyticsRepository_TeamStats_Call{Call: _e.mock.On("TeamStats", ctx, actorID, doneWindowDays)}
}

func (_c *MockAnalyticsRepository_TeamStats_Call) Run(run func(ctx context.Context, actorID int64, doneWindowDays int)) *MockAnalyticsRepository_TeamStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalyticsRepository_TeamStats_Call) Return(teamStatss []domain.TeamStats, err error) *MockAnalyticsRepository_TeamStats_Call {
	_c.Call.Return(teamStatss, err)
	return _c
}

func (_c *MockAnalyticsRepository_TeamStats_Call) RunAndReturn(run func(ctx context.Context, actorID int64, doneWindowDays int) ([]domain.TeamStats, error)) *MockAnalyticsRepository_TeamStats_Call {
	_c.Call.Return(run)
	return _c
}

// TopCreators provides a mock function for the type MockAnalyticsRepository
func (_mock *MockAnalyticsRepository) TopCreators(ctx context.Context, actorID int64, windowDays int, limit int) ([]domain.TeamTopCreator, error) {
	ret := _mock.Called(ctx, actorID, windowDays, limit)

	if len(ret) == 0 {
		panic("no return value specified for TopCreators")
	}

	var r0 []domain.TeamTopCreator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]domain.TeamTopCreator, error)); ok {
		return returnFunc(ctx, actorID, windowDays, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) []domain.TeamTopCreator); ok {
		r0 = returnFunc(ctx, actorID, windowDays, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TeamTopCreator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = returnFunc(ctx, actorID, windowDays, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsRepository_TopCreators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TopCreators'
type MockAnalyticsRepository_TopCreators_Call struct {
	*mock.Call
}

// TopCreators is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID int64
//   - windowDays int
//   - limit int
func (_e *MockAnalyticsRepository_Expecter) TopCreators(ctx any, actorID any, windowDays any, limit any) *MockAnalyticsRepository_TopCreators_Call {
	return &MockAnalyticsRepository_TopCreators_Call{Call: _e.mock.On("TopCreators", ctx, actorID, windowDays, limit)}
}

func (_c *MockAnalyticsRepository_TopCreators_Call) Run(run func(ctx context.Context, actorID int64, windowDays int, limit int)) *MockAnalyticsRepository_TopCreators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAnalyticsRepository_TopCreators_Call) Return(teamTopCreators []domain.TeamTopCreator, err error) *MockAnalyticsRepository_TopCreators_Call {
	_c.Call.Return(teamTopCreators, err)
	return _c
}

func (_c *MockAnalyticsRepository_TopCreators_Call) RunAndReturn(run func(ctx context.Context, actorID int64, windowDays int, limit int) ([]domain.TeamTopCreator, error)) *MockAnalyticsRepository_TopCreators_Call {
	_c.Call.Return(run)
	return _c
}
