// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_login

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(ctx any, email any) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(user domain.User, err error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (domain.User, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordVerifier creates a new instance of MockPasswordVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordVerifier {
	mock := &MockPasswordVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordVerifier is an autogenerated mock type for the PasswordVerifier type
type MockPasswordVerifier struct {
	mock.Mock
}

type MockPasswordVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordVerifier) EXPECT() *MockPasswordVerifier_Expecter {
	return &MockPasswordVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockPasswordVerifier
func (_mock *MockPasswordVerifier) Verify(hash string, password string) error {
	ret := _mock.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hash, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPasswordVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *MockPasswordVerifier_Expecter) Verify(hash any, password any) *MockPasswordVerifier_Verify_Call {
	return &MockPasswordVerifier_Verify_Call{Call: _e.mock.On("Verify", hash, password)}
}

func (_c *MockPasswordVerifier_Verify_Call) Run(run func(hash string, password string)) *MockPasswordVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordVerifier_Verify_Call) Return(err error) *MockPasswordVerifier_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordVerifier_Verify_Call) RunAndReturn(run func(hash string, password string) error) *MockPasswordVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIssuer creates a new instance of MockTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIssuer {
	mock := &MockTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenIssuer is an autogenerated mock type for the TokenIssuer type
type MockTokenIssuer struct {
	mock.Mock
}

type MockTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIssuer) EXPECT() *MockTokenIssuer_Expecter {
	return &MockTokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type MockTokenIssuer
func (_mock *MockTokenIssuer) Issue(userID int64) (string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) string); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - userID int64
func (_e *MockTokenIssuer_Expecter) Issue(userID any) *MockTokenIssuer_Issue_Call {
	return &MockTokenIssuer_Issue_Call{Call: _e.mock.On("Issue", userID)}
}

func (_c *MockTokenIssuer_Issue_Call) Run(run func(userID int64)) *MockTokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) Return(s string, err error) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) RunAndReturn(run func(userID int64) (string, error)) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}
