// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package task_history_get

import (
	"context"
	"team-taskflow/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskAccess creates a new instance of MockTaskAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskAccess {
	mock := &MockTaskAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskAccess is an autogenerated mock type for the TaskAccess type
type MockTaskAccess struct {
	mock.Mock
}

type MockTaskAccess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskAccess) EXPECT() *MockTaskAccess_Expecter {
	return &MockTaskAccess_Expecter{mock: &_m.Mock}
}

// LoadTaskForMember provides a mock function for the type MockTaskAccess
func (_mock *MockTaskAccess) LoadTaskForMember(ctx context.Context, taskID int64, actorID int64) (domain.Task, error) {
	ret := _mock.Called(ctx, taskID, actorID)

	if len(ret) == 0 {
		panic("no return value specified for LoadTaskForMember")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (domain.Task, error)); ok {
		return returnFunc(ctx, taskID, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) domain.Task); ok {
		r0 = returnFunc(ctx, taskID, actorID)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, taskID, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskAccess_LoadTaskForMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadTaskForMember'
type MockTaskAccess_LoadTaskForMember_Call struct {
	*mock.Call
}

// LoadTaskForMember is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int64
//   - actorID int64
func (_e *MockTaskAccess_Expecter) LoadTaskForMember(ctx any, taskID any, actorID any) *MockTaskAccess_LoadTaskForMember_Call {
	return &MockTaskAccess_LoadTaskForMember_Call{Call: _e.mock.On("LoadTaskForMember", ctx, taskID, actorID)}
}

func (_c *MockTaskAccess_LoadTaskForMember_Call) Run(run func(ctx context.Context, taskID int64, actorID int64)) *MockTaskAccess_LoadTaskForMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskAccess_LoadTaskForMember_Call) Return(task domain.Task, err error) *MockTaskAccess_LoadTaskForMember_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskAccess_LoadTaskForMember_Call) RunAndReturn(run func(ctx context.Context, taskID int64, actorID int64) (domain.Task, error)) *MockTaskAccess_LoadTaskForMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHistoryRepository creates a new instance of MockHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHistoryRepository {
	mock := &MockHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHistoryRepository is an autogenerated mock type for the HistoryRepository type
type MockHistoryRepository struct {
	mock.Mock
}

type MockHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHistoryRepository) EXPECT() *MockHistoryRepository_Expecter {
	return &MockHistoryRepository_Expecter{mock: &_m.Mock}
}

// ListByTask provides a mock function for the type MockHistoryRepository
func (_mock *MockHistoryRepository) ListByTask(ctx context.Context, taskID int64) ([]domain.TaskHistoryEntry, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTask")
	}

	var r0 []domain.TaskHistoryEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]domain.TaskHistoryEntry, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []domain.TaskHistoryEntry); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TaskHistoryEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHistoryRepository_ListByTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTask'
type MockHistoryRepository_ListByTask_Call struct {
	*mock.Call
}

// ListByTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID int64
func (_e *MockHistoryRepository_Expecter) ListByTask(ctx any, taskID any) *MockHistoryRepository_ListByTask_Call {
	return &MockHistoryRepository_ListByTask_Call{Call: _e.mock.On("ListByTask", ctx, taskID)}
}

func (_c *MockHistoryRepository_ListByTask_Call) Run(run func(ctx context.Context, taskID int64)) *MockHistoryRepository_ListByTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHistoryRepository_ListByTask_Call) Return(taskHistoryEntrys []domain.TaskHistoryEntry, err error) *MockHistoryRepository_ListByTask_Call {
	_c.Call.Return(taskHistoryEntrys, err)
	return _c
}

func (_c *MockHistoryRepository_ListByTask_Call) RunAndReturn(run func(ctx context.Context, taskID int64) ([]domain.TaskHistoryEntry, error)) *MockHistoryRepository_ListByTask_Call {
	_c.Call.Return(run)
	return _c
}
